### ISSUE TITLE
Set Name & Surname 

### ISSUE THREAD

**Issue by akbarjorayev** [akbarjorayev/akbarjorayevaj#2]

**Comment by kaiyumdev** [comment]
do you have any specific guideline or readme to contribute this project?

**Comment by akbarjorayev** [comment]
> do you have any specific guideline or readme to contribute this project?

I am making this for my Portfolio. Do you want to join?

**Comment by kaiyumdev** [comment]
Yes, of course.

**Comment by akbarjorayev** [comment]
> Yes, of course.

Where we can have chat? Telegram or Instagram? Can you give me your username...

**Comment by kaiyumdev** [comment]
kaiyumdev is my username of instagram, twitter, linkedin

**Comment by akbarjorayev** [comment]
> kaiyumdev is my username of instagram, twitter, linkedin

I wrote to you on Instagram
